### ISSUE TITLE
mediaBrowser.connect()  crash

### ISSUE THREAD

**Issue by lsp19880926** [android/uamp#251] opened 2018-09-25 09:32 UTC
In android 8.0 or above, I met a problem.

when i called MediaBrowser.connect() ,it will crash sometimes.

`Caused by java.lang.IllegalStateException: connect() called while neither disconnecting nor disconnected (state=CONNECT_STATE_CONNECTING)
       at android.media.browse.MediaBrowser.connect(MediaBrowser.java:152)
       at android.support.v4.media.MediaBrowserCompatApi21.connect(Unknown Source:2)
       at android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21.connect(Unknown Source:2)
       at android.support.v4.media.MediaBrowserCompat.connect(Unknown Source:2)`

Looks like  connect() being called multiple times.But I called disconnect() in onStop().

I can't reproduce it ,I just saw it in the fabric log.

**Comment by noname2534** [comment] 2018-09-26 18:29
+1

**Comment by viper123** [comment] 2018-12-06 04:45
I have also encounter this problem on Android 7 and Android 4.4

**Comment by rczhang13028** [comment] 2019-05-24 07:26
I have also encounter this problem. How can i get the connect state,and i can use connect state avoid this crash.

**Comment by rczhang13028** [comment] 2019-05-24 07:31
I have also encounter this problem。How can i get the connect state,and i want use connect state avoid this crash。
Examle:
if(mediaBrowser.getConnectState() != CONNECT_STATE_CONNECTING && !mediaBrowser.isConnected){
	mediaBrowser.connect()
}

**Comment by Flyktsodan** [comment] 2019-10-18 12:05
Anyone have any update on how to solve this?
We have been using UAMP as a reference on how we implement our player and we have the same issue.

**Comment by Subuday** [comment] 2019-11-19 15:01
The same problem on Android 8.1

**Comment by Subuday** [comment] 2019-12-01 23:19
> 
> 
> I have also encounter this problem。How can i get the connect state,and i want use connect state avoid this crash。
> Examle:
> if(mediaBrowser.getConnectState() != CONNECT_STATE_CONNECTING && !mediaBrowser.isConnected){
> mediaBrowser.connect()
> }

Use this code in try catch block.

**Comment by finneapps** [comment] 2020-06-10 08:39
but what state will this leave the app in? if you just catch the Exception?

**Comment by nic0lette** [comment] 2020-12-04 14:36
After some further digging into this, it seems to not be a UAMP specific issue, and since there doesn't seem to be a way to consistently reproduce it, I'm going to close this, rather than attempt to put in a work around that may/may not work.

**Closed by nic0lette** 2020-12-04 14:36 UTC
Labels: bug
