### ISSUE TITLE
gradle failed to sync due to unresolved dependencies

### ISSUE THREAD

**Issue by tmooner** [android/uamp#296] opened 2019-07-24 14:44 UTC
I just downloaded the java jdk 12.0.2, I downloaded android studios 3.4.2 and it came with gradle 5.1.1 pre-installed. The very first time I tried to run gradle it failed to sync due to unresolved dependencies. Does anyone know what I did wrong? I thought I followed the YouTube tutorial verbatim but I cant even start to program.

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve androidx.appcompat:appcompat:1.0.2. Show Details Affected Modules: app |  
-- | --
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve androidx.core:core-ktx:1.0.2. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve androidx.constraintlayout:constraintlayout:1.1.3. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.android.material:material:1.0.0. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve androidx.test:runner:1.2.0. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve androidx.test.espresso:espresso-core:3.2.0. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve androidx.appcompat:appcompat:1.0.2. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve androidx.core:core-ktx:1.0.2. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve androidx.constraintlayout:constraintlayout:1.1.3. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.android.material:material:1.0.0. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve androidx.appcompat:appcompat:1.0.2. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve androidx.core:core-ktx:1.0.2. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve androidx.constraintlayout:constraintlayout:1.1.3. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.android.material:material:1.0.0. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve junit:junit:4.12. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve androidx.appcompat:appcompat:1.0.2. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve androidx.core:core-ktx:1.0.2. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve androidx.constraintlayout:constraintlayout:1.1.3. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.android.material:material:1.0.0. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve androidx.appcompat:appcompat:1.0.2. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve androidx.core:core-ktx:1.0.2. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve androidx.constraintlayout:constraintlayout:1.1.3. Show Details Affected Modules: app |

**Comment by thibseisel** [comment] 2019-08-29 15:29
Are you working behind a proxy ? This is quite common in corporate environnements.
If that's the case, you should modify the `repositories` block in the root `build.gradle` to add a Maven remote repository (such as Nexus) :

```gradle
buildscript {
    repositories {
        maven { url 'https://my.nexus.com/maven2' }
        google()
        jcenter()
    }
}

allprojects {
    repositories {
        maven { url 'https://my.nexus.com/maven2' }
        google()
        jcenter()
    }
}
```
If you are not working behind a proxy or the above fix did not work, please run ```./gradlew app:assembleDebug --info``` to find out what prevents you from resolving dependencies.

**Comment by dturner** [comment] 2020-12-04 12:36
Cannot reproduce.

**Closed by dturner** 2020-12-04 12:36 UTC
